# Generated by Django 5.1.6 on 2025-03-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
