# Generated by Django 5.1.6 on 2025-03-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_thumbnail_alter_author_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
