# Generated by Django 5.1.6 on 2025-03-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Source',
            field=models.TextField(blank=True, help_text='Enter the book online link for more deatils and buy link', null=True),
        ),
    ]
